---
title: "Compare VAST and survey planktivores"
author: "Sarah Gaichas"
date: "2022-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
```


Compare SOE aggregate survey bio indices to VAST forage index. Caveats: may not contain same species, wont be on same scale

## Compare indices scaled to mean for each EPU

Use Kim B's code to extract planktivores from `ecodata::aggregate_biomass`, modify code to calculate time series sd, rescale

```{r SOEplanktivores}
planktivores <- ecodata::aggregate_biomass %>%
  dplyr::filter(Var %in% c("Planktivore Fall Biomass Index",
                           "Planktivore Spring Biomass Index",
                           "Planktivore Fall Biomass Standard Error",
                           "Planktivore Spring Biomass Standard Error"))%>%
  tidyr::separate(Var, c("feeding.guild", "season", "Biomass", "Var1", "Null", "Area"), sep = " ") %>%
  tidyr::unite("Var", feeding.guild:season, sep = " ") %>%
  dplyr::mutate(stat = recode(Var1, Index = "Mean",
                      Standard = "SD")) %>%
  dplyr::select(-Biomass, -Var1, -Null, -Units) %>%
  # dplyr::filter(!Area == "-") %>%
  dplyr::group_by(Var, Time, EPU, Area) %>%
  tidyr::pivot_wider(id_cols = c(Var, Time, EPU, Area),names_from =  stat, values_from =  Value) %>%
  dplyr::filter(!Mean == "NULL") %>%
  dplyr::ungroup() %>%
  dplyr::mutate(Mean = as.numeric(Mean))


agg_bio<-planktivores %>% dplyr::filter(EPU %in% c("MAB", "GB", "GOM"),
         Time >= 1968) %>%
  dplyr::group_by(Var, EPU) %>%
  dplyr::mutate(hline = mean(Mean, na.rm = T), 
                tssd = sd(SD, na.rm = T),
                 upper = Mean + (2*SD),
                lower = Mean - (2*SD)) %>%
  dplyr::ungroup()  

agg_bio_std <- agg_bio %>%
  dplyr::mutate(stdPlank = (Mean-hline)/tssd,
                cv = SD/Mean,
                stdPlankupper = ,
                stdPlanklower = )
```

## Compare species lists