---
title: "Bluefish Diet Analyses for 2022 RTA"
author: "Sarah Gaichas"
output: html_document
---

<button>
    <a href="https://github.com/sgaichas/bluefishdiet"> Bluefish Forage Index Repo </a>
</button>


<!-- ADD LINKS BELOW, note, using the RMD link syntax will open the presentation in the same tab, which is annoying. Use the html with the "_blank" to fix that behavior -->

## Analysis pages
 

<a href="https://sgaichas.github.io/bluefishdiet/DietSummary.html" target="_blank"> Initial Diet summaries for NEFSC data - Nov 10 2021 </a>

<a href="https://sgaichas.github.io/bluefishdiet/ForageIndex.html" target="_blank"> Forage Index Development - November 10 2021 </a>

<a href="https://sgaichas.github.io/bluefishdiet/PiscPESCbySL.html" target="_blank"> Scott's trial PESC model - November 18 2021 </a>

<a href="https://sgaichas.github.io/bluefishdiet/PreyAggs.html" target="_blank"> How to group prey across predators - December 6 2021 </a>

<a href="https://sgaichas.github.io/bluefishdiet/VASTmod1.html" target="_blank"> Try VAST index all prey aggregated - December 6 2021 </a>

<a href="https://sgaichas.github.io/bluefishdiet/VASTmod2.html" target="_blank"> Working VAST index all prey aggregated with results - January 7 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/VASTmodsel.html" target="_blank"> Evaluate different model structures using AIC, NEFSC data only - January 19 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/AddNEAMAP.html" target="_blank"> Working on adding NEAMAP survey - February 2 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/DataMeetingSummary.html" target="_blank"> Summary of progress for data meeting - February 14 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/PreySimilarityUpdate.html" target="_blank"> Update feeding guilds - February 15 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/UpdateVAST_Inputs.html" target="_blank"> Update VAST input dataset with new predator list - February 23 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/VASTmodsel_updatedPreds.html" target="_blank"> Update VAST model selection, both surveys, new predator list - February 23 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/VASTcovariates_updatedPreds.html" target="_blank"> Update VAST covariate selection, both surveys, new predator list - March 1 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/InshoreOffshoreDefs.html" target="_blank"> Spilt outputs to different inshore and offshore strata - March 21 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/RegionalIndices.html" target="_blank"> Update inshore and offshore strata - April 11 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/SSTmethods.html" target="_blank"> Get OISST and merge with VAST input data - May 6 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/VASTcovariates_updatedPreds_sst.html" target="_blank"> Update VAST covariate selection with SST, both surveys, new predator list - June 8 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/VASTcovariates_updatedPreds_sst_3mi.html" target="_blank"> Update VAST spatial splits with state waters/federal waters - June 13 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/VASTcovariates_finalmod_survstrat.html" target="_blank"> Bias corrected index for partitions based on survey strata - July 11 2022 </a>

<a href="https://sgaichas.github.io/bluefishdiet/VASTcovariates_finalmod_strattest.html" target="_blank"> Me worrying (unnecessarily?) about strata.limits - July 15 2022 </a>
